### ISSUE TITLE
No virtual method setBaseUrl

### ISSUE THREAD

**Issue by colgao** [mapbox/mapbox-vision-android-teaser#142]
2019-10-18 10:27:04.089 19715-19715/com.mapbox.vision.teaser.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.vision.teaser.debug, PID: 19715
    java.lang.NoSuchMethodError: No virtual method setBaseUrl(Ljava/lang/String;)V in class Lcom/mapbox/android/telemetry/MapboxTelemetry; or its super classes (declaration of 'com.mapbox.android.telemetry.MapboxTelemetry' appears in /data/app/com.mapbox.vision.teaser.debug-vsguZClt4EedU74PIkQR9g==/base.apk!classes3.dex)
        at com.mapbox.vision.sync.SessionManager$Impl.configMapboxTelemetry(SessionManager.kt:191)
        at com.mapbox.vision.sync.SessionManager$Impl.setCountry(SessionManager.kt:100)
        at com.mapbox.vision.VisionManager$start$3$1.run(VisionManager.kt:288)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by colgao** [comment]
it can not run where GPS is valid in Vision SDK(0.9.0,0.10.0,0.10.1)

**Comment by yunikkk** [comment]
Hey @colgao , which versions of other mapbox libraries do you use? Could you paste resolved dependencies list from gradle (eg. `./gradlew dependencies`) ?

**Comment by colgao** [comment]
from 0.9.0，0.10.0     0.10.1 ，debug ,
    implementation(name: "mapbox-vision-all_$vision/mapbox-android-vision-ar-release", ext: 'aar')
    implementation(name: "mapbox-vision-all_$vision/mapbox-android-vision-release", ext: 'aar')
    implementation(name: "mapbox-vision-all_$vision/mapbox-android-vision-safety-release", ext: 'aar')

**Comment by colgao** [comment]
at 0.9.0，0.10.0 , 0.10.1 ，debug build
implementation(name: "mapbox-vision-all_$vision/mapbox-android-vision-ar-release", ext: 'aar')
implementation(name: "mapbox-vision-all_$vision/mapbox-android-vision-release", ext: 'aar')
implementation(name: "mapbox-vision-all_$vision/mapbox-android-vision-safety-release", ext: 'aar')

**Comment by 164933716** [comment]
> at 0.9.0，0.10.0 , 0.10.1 ，debug build
> implementation(name: "mapbox-vision-all_$vision/mapbox-android-vision-ar-release", ext: 'aar')
> implementation(name: "mapbox-vision-all_$vision/mapbox-android-vision-release", ext: 'aar')
> implementation(name: "mapbox-vision-all_$vision/mapbox-android-vision-safety-release", ext: 'aar')

Modify or add:
implementation "com.mapbox.mapboxsdk:mapbox-android-telemetry:4.6.0"

**Comment by colgao** [comment]
thinks ！

**Comment by colgao** [comment]
OK！thinks！

**Comment by yunikkk** [comment]
Thanks @164933716 , indeed this dependency is missing if libraries are downloaded directly, not via maven dependency. We'll add this statement to the docs.
