### ISSUE TITLE
 java.lang.IllegalStateException: CameraDevice was already closed

### ISSUE THREAD

**Issue by praveendeshmane** [mapbox/mapbox-vision-android-teaser#154]
```
`override fun onStart() {
        super.onStart()
        logger!!.addRecordToLog("onStart()")
        startVisionManager()
        //startNavigation()
    }

    override fun onResume() {
        super.onResume()
        logger!!.addRecordToLog("onResume()")
        mapbox_ar_view.onResume()
        startNavigation()
        //startVisionManager()
    }

    override fun onPause() {
        super.onPause()
        logger!!.addRecordToLog("onPause()")
        mapbox_ar_view.onPause()
        stopNavigation()
    }

    override fun onStop() {
        super.onStop()
        stopVisionManager()
        //stopVisionManager()
    }

    private fun startVisionManager() {
        logger!!.addRecordToLog("startVisionManager()")
        if (allPermissionsGranted() && !visionManagerWasInit) {
            // Create and start VisionManager.
            VisionManager.create()
            VisionManager.start()
            VisionManager.setModelPerformanceConfig(Merged(On(ModelPerformanceMode.DYNAMIC, ModelPerformanceRate.LOW)))

            //record video
            /*  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd_HH-mm-ssZ", Locale.getDefault());
            String currentDateAndTime = sdf.format(new Date());
            String path = "/sdcard/Project_ARNavigation/Video_" + currentDateAndTime;
            VisionManager.startRecording(path);
*/
            // Create VisionArManager.
            VisionArManager.create(VisionManager)
            mapbox_ar_view.setArManager(VisionArManager)
            // Create and start VisionManager.
            VisionSafetyManager.create(VisionManager)
            VisionSafetyManager.visionSafetyListener = visionSafetyListener
            VisionManager.visionEventsListener = visionEventsListener
            visionManagerWasInit = true
        }
    }

    private fun stopVisionManager() {
        logger!!.addRecordToLog("stopVisionManager()")
        if (visionManagerWasInit) {
            //stop recording video
            VisionArManager.destroy()
            VisionSafetyManager.destroy()
            VisionManager.stop()
            VisionManager.destroy()
            visionManagerWasInit = false
        }
    }


    private fun startNavigation() {
        logger!!.addRecordToLog("startNavigation()")
        if (allPermissionsGranted() && !navigationWasStarted) {
            try {
                arLocationEngine!!.requestLocationUpdates(arLocationEngineRequest, locationCallback, Looper.getMainLooper())
            } catch (se: SecurityException) {
                VisionLogger.e(TAG, se.toString())
            }
            // Route need to be reestablished if off route happens.
            mapboxNavigation!!.addOffRouteListener(this)
            mapboxNavigation!!.addProgressChangeListener(this)
            mapboxNavigation!!.addNavigationEventListener(this)
            mapboxNavigation!!.addMilestoneEventListener(this)
            //start
            mapboxNavigation!!.addMilestone(StepMilestone.Builder()
                    .setIdentifier(BEGIN_ROUTE_MILESTONE)
                    .setInstruction(BeginRouteInstruction())
                    .setTrigger(
                            Trigger.eq(TriggerProperty.FIRST_STEP, TriggerProperty.TRUE)
                    )
                    .build()
            )
            //step change
            mapboxNavigation!!.addMilestone(StepMilestone.Builder()
                    .setIdentifier(NEW_ROUTE_MILESTONE)
                    .setInstruction(MilestoneInstruction())
                    .setTrigger(
                            Trigger.all(
                                    Trigger.eq(TriggerProperty.NEW_STEP, TriggerProperty.TRUE),
                                    Trigger.neq(TriggerProperty.FIRST_STEP, TriggerProperty.TRUE),
                                    Trigger.neq(TriggerProperty.LAST_STEP, TriggerProperty.TRUE))).build()
            )
            //end
            mapboxNavigation!!.addMilestone(StepMilestone.Builder()
                    .setIdentifier(END_ROUTE_MILESTONE)
                    .setInstruction(EndRouteInstruction())
                    .setTrigger(
                            Trigger.all(
                                    Trigger.eq(TriggerProperty.LAST_STEP, TriggerProperty.TRUE))).build()
            )
            //distance remaining
            mapboxNavigation!!.addMilestone(StepMilestone.Builder()
                    .setIdentifier(DISTANCE_REMAINING_ROUTE)
                    .setInstruction(DistanceRemainingInstruction())
                    .setTrigger(
                            Trigger.all(
                                    Trigger.eq(TriggerProperty.LAST_STEP, TriggerProperty.TRUE),
                                    Trigger.lte(TriggerProperty.STEP_DISTANCE_REMAINING_METERS, 0))).build()
            )
            initDirectionsRoute()
            navigationWasStarted = true
        }
    }

    private fun stopNavigation() {
        logger!!.addRecordToLog("stopNavigation()")
        if (navigationWasStarted) {
            arLocationEngine!!.removeLocationUpdates(locationCallback!!)
            mapboxNavigation!!.removeProgressChangeListener(this)
            mapboxNavigation!!.removeOffRouteListener(this)
            mapboxNavigation!!.removeMilestoneEventListener(this)
            mapboxNavigation!!.removeNavigationEventListener(this)
            mapboxNavigation!!.stopNavigation()
            navigationWasStarted = false
        }
    }
`
```

**Comment by kiryldz** [comment]
Hi @praveendeshmane !
Thanks for reporting, could you please specify if this crash always happens at some specific moment of time or just occasionally. It would also pretty useful to have error log here - exception `java.lang.IllegalStateException: CameraDevice was already closed` most likely is thrown after some another crash in native, it should be somewhere before this exception in logs.

**Comment by praveendeshmane** [comment]
@kiryldz 
Thank you for your reply. It happens when we go back from ARActivity to MapActivity by clicking back button. Not every time it happens, happens only every third time or fourth time moving from MapActivity to ArActivity and vice versa. I am destroying the VisionArManager, VisionSafetyManager, VisionManager in onStop() method, I don't know is it right way or not, according to vision teaser it is exactly the same. Below is complete log of crash. Please help me out. 

`I/MediaRecorderJNI: stop
I/MediaRecorderJNI: native_reset
D/SensorManager: unregisterListener ::   
D/ConnectivityManager: unregisterNetworkCallback; CallingUid : 10134, CallingPid : 26498

E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: jp.mcapps.arnavigation, PID: 26498
    java.lang.IllegalStateException: CameraDevice was already closed
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2432)
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:783)
        at com.mapbox.vision.video.videosource.camera.Camera2VideoSourceImpl.createCaptureSession(Camera2VideoSourceImpl.kt:165)
        at com.mapbox.vision.video.videosource.camera.Camera2VideoSourceImpl.access$createCaptureSession(Camera2VideoSourceImpl.kt:25)
        at com.mapbox.vision.video.videosource.camera.Camera2VideoSourceImpl$createCaptureSession$$inlined$let$lambda$1.updateSession(Camera2VideoSourceImpl.kt:174)
        at com.mapbox.vision.video.videosource.camera.Camera2VideoSourceImpl$createCaptureSession$$inlined$let$lambda$1.onClosed(Camera2VideoSourceImpl.kt:217)
        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onClosed$5(CallbackProxies.java:104)
        at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$9H0ZdANdMrdpoq2bfIL2l3DVsKk.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
I/Process: Sending signal. PID: 26498 SIG: 9
Process 26498 terminated.
`

**Comment by praveendeshmane** [comment]
please help me out.

**Comment by kiryldz** [comment]
Hi @praveendeshmane ! We are aware of this issue. This should be fixed in new release coming out first half January.

**Comment by praveendeshmane** [comment]
Hi @kiryldz ! is this bug solved and released?

**Comment by kiryldz** [comment]
Hi @praveendeshmane , we actually released new version 0.11.0 of Vision but did not update Teaser yet.
However you could manually change version in `build.gradle` app-level to 0.11.0 and try build Teaser from  `dev` brach - it should work fine.

**Comment by praveendeshmane** [comment]
@kiryldz , I will check and let you know. Thank you for your time and support. I appreciate it.

**Comment by kiryldz** [comment]
@praveendeshmane - how is it going?
