### ISSUE TITLE
[Crash Report] App crashes on tapping ARRouting

### ISSUE THREAD

**Issue by knightcube** [mapbox/mapbox-vision-android-teaser#47]
### Steps to reproduce the error
1. Open app on phone
2. Tap on AR Routing
3. Map does not load 
4. Press back arrow
5. App crashes

Here are the logs - 
```
`java.lang.RuntimeException: Unable to stop activity {com.mapbox.vision.examples.debug/com.mapbox.vision.examples.activity.ar.ArMapActivity}: kotlin.UninitializedPropertyAccessException: lateinit property locationEngine has not been initialized
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4178)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4148)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4223)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:192)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property locationEngine has not been initialized
        at com.mapbox.vision.examples.activity.ar.ArMapActivity.onStop(ArMapActivity.kt:87)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1433)
        at android.app.Activity.performStop(Activity.java:7367)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4170)`
```

**Comment by knightcube** [comment]
Fixed this crash by adding mapbox access key

In Project Hierarchy:
mapbox-vision-android-teaset > app > src > main > res > values > developer-config.xml

**Comment by VanJoshElanium** [comment]
> Fixed this crash by adding mapbox access key
> 
> In Project Hierarchy:
> mapbox-vision-android-teaset > app > src > main > res > values > developer-config.xml

Is the "mapbox access key" the mapbox token key?
